#!/bin/sh

case "$1" in
    start)
        scull_load
        module_load faulty
        modprobe hello
        ;;
    stop)
        scull_unload
        module_unload faulty
        rmmod hello
        ;;
    *)
        echo "invalid argument"
        exit 1
        ;;
esac

exit 0
